create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  company text,
  niche text,
  city text,
  phone text,
  instagram text,
  maps_link text,
  website text,
  score int4,
  status text,
  source text,
  notes text
);

alter table public.leads enable row level security;

drop policy if exists "service insert leads" on public.leads;
create policy "service insert leads"
on public.leads
for insert
with check (true);

drop policy if exists "read leads" on public.leads;
create policy "read leads"
on public.leads
for select
using (true);
